### PR TITLE
docs: remove redundant $ from terminal command

### PR DESCRIPTION
**Pull request by Akirtovskis**
Removing the unnecessary $ from terminal commands.

Referring to : https://github.com/blockstack/docs/issues/1190

### CODE REVIEW

**Review by wileyj — COMMENTED** [review]
This should remain unchanged since it shows the command as well as the expected output

**Comment by Akirtovskis** [comment]
@wileyj Sorry for the late response. My understanding was that for these we split out the command and output in two blocks, so it is still easy to copy the command right away. If that's not the case I can close the PRs where I did it wrong.

**Comment by wileyj** [comment]
> @wileyj Sorry for the late response. My understanding was that for these we split out the command and output in two blocks, so it is still easy to copy the command right away. If that's not the case I can close the PRs where I did it wrong.

I would confirm with @pgray-hiro  here, but that's my understanding - standalone commands would have the `$` removed, but if the text shows a command and the output, it would keep the `$`. 
ex:
**commands:**
```
echo "foo"
echo "bar
```
**commands with output:**
```
$ echo "foo"
foo
$ echo "bar"
bar
```

**Comment by gray-patrick** [comment]
Yes, what @wileyj said as an example is correct. One final example would be to separate the example command from the example output with expository text, such as:

"Enter the following command to print text to the terminal:

```
echo "foo"
```

You should receive the following output:

```
foo
```
"

**Comment by Akirtovskis** [comment]
@gray-patrick @wileyj  Sorry for taking this long to respond. Updated according to your suggestions. 

Also did the same updates for this one : https://github.com/blockstack/subdomain-registrar/pull/62

**Review by wileyj — APPROVED** [review]

**Pull request merged**
