### PR TITLE
docs: remove $ from cmd so it is easier to paste in terminal

### PR DESCRIPTION
**Pull request by Akirtovskis**
Just a suggestion as I found it a bit tedious to delete $ after pasting every single command into my terminal.

## Description
**1. Motivation for change**
Easier to run commands after pasting into the terminal
**2. What was changed**
Removed the $ sign from the setup commands
**3. How do these changes impact application developers**
Speeds up their experience

### CODE REVIEW

**Comment by Akirtovskis** [comment]
@wileyj heya, tagging you here because I saw that you have most contributions in this repo.

**Comment by wileyj** [comment]
@Akirtovskis Thanks for the PR!

The reason the `$` are listed here is quite simply - that's the way it's been done elsewhere in a lot of our docs. 
I agree with this change, but before I can merge it I want to discuss with other team members to see if we should globally institute this.

**Comment by Akirtovskis** [comment]
Thanks for getting back so quickly and that absolutely makes sense. If you decide that there's a need to change this globally I am happy to help with that.

**Comment by wileyj** [comment]
will do! 
i'm in fact creating a new issue in our docs repo to address this. Once i have that ticket created i'll share here and we can merge this. 

thanks again!

**Pull request merged**
